apiVersion: integration/v1
kind: Integration
name: github
channel: alpha
version: v20200515
summary: GitHub
license: Apache-2.0
homepage: https://github.com/relay-integrations/relay-github
source: https://github.com/relay-integrations/relay-github

description: |
  GitHub is a Git repository hosting service and collaboration tool.

owner:
  name: Puppet, Inc.
  email: relay@puppet.com
  url: https://puppet.com

tags:
  - source control
  - git
  - github
  - relay integration
