apiVersion: integration/v1
kind: Trigger
name: github-trigger-event-sink
version: 1
summary: GitHub Event sink

description: |
  This trigger takes in the contents of a github event and presents it as an output event

responders:
- webhook

schemas:
  spec:
    $schema: http://json-schema.org/draft-07/schema#

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/github-trigger-event-sink
