apiVersion: integration/v1
kind: Trigger
name: github-trigger-event-sink
version: 1
summary: GitHub event fired

description: |
  This trigger takes in the contents of a github event and presents it as an output event

responders:
- webhook

schemas:
  event:
    source: file
    file: event.schema.json

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/github-trigger-event-sink

examples:
- summary: When a GitHub event fires
  content:
    apiVersion: v1
    kind: Trigger
    name: github-trigger-event
    source:
      type: webhook
      image: relaysh/github-trigger-event-sink
    binding:
      parameters:
        event_payload: !Data event_payload