apiVersion: container/v1
kind: StepContainer
inherit: {from: sdk, name: python.v1}
title: Github PR Merged Trigger
description: >
  This trigger fires when a GitHub PR is merged.
settings:
  CommandPath: server.py
  AdditionalPythonPackages:
  - quart
